name: Add comment
on:
  issues:
    types:
      - opened
jobs:
  add-comment:
    if: github.event.label.name == 'needs approval'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            :sparkles: Thank you for requesting an invitation! :sparkles:
            A maintainer will verify your Bookface profile and keep you posted.
